### PR TITLE
Add some icons glyph

### PR DESCRIPTION
**Pull request by pc223**
@taooceros Do you want to handle icons like this? Add the glyph directly in the json file?

I managed to get some of the icon out of this file, a lot still missing, I'll try a bit more later

C:\Windows\ImmersiveControlPanel\Settings\AllSystemSettings_{253E530E-387D-4BC2-959D-E6F86122E5F2}.xml

### CODE REVIEW

**Comment by taooceros** [comment]
Wow, interesting. Will take a look soon.

**Comment by taooceros** [comment]
I check the glyph. It may requires more edition for now (add a property for Result display in ResultListView). We need to make a proposal for that in Flow because these glyph requires extra assets font.

**Comment by pc223** [comment]
> I check the glyph. It may requires more edition for now (add a property for Result display in ResultListView). We need to make a proposal for that in Flow because these glyph requires extra assets font.

Yeah, it's this font

https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font

**Comment by taooceros** [comment]
I check for dynamic font import. It looks like it is possible to directly import a ttf into the application, but it also contains an issue that needs to be aware.
https://stackoverflow.com/questions/48609956/change-font-family-programmatically-in-wpf
https://stackoverflow.com/questions/31452443/wpf-textblock-memory-leak-when-using-font

**Comment by taooceros** [comment]
@pc223 Could you add glyph to a different field in the json, because the glyph may require a special font family.

**Comment by pc223** [comment]
> @pc223 Could you add glyph to a different field in the json, because the glyph may require a special font family.

Like this?

```JSON
{
	...
	"IconGlyph": { 
		"Glyph": "\ue8d7",
		"FontFamily": "Segoe MDL2 Assets"
	}
	...
}
```

**Comment by taooceros** [comment]
@pc223 Do you want to finish the glyph icon results by yourselves? I can handle it if that's too hard😃.

**Comment by pc223** [comment]
> @pc223 Do you want to finish the glyph icon results by yourselves? I can handle it if that's too hard😃.

Yeah, you just go ahead and complete this I think :smile: It's enough for early release, I'll look closer later to see if I can get some more glyphs, for now still quite a bit missing 😄

**Comment by taooceros** [comment]
I will merge it first

**Pull request merged**
