### PR TITLE
Add task links

### PR DESCRIPTION
**Pull request by pc223**
I'm trying to add task links into this plugin, you can use this as starting point 😄

### CODE REVIEW

**Comment by taooceros** [comment]
Could you simply add task link to WindowsSettings.json instead of creating a new json file, but with a different Type? That will reduce the codebase we need to take care on.😉

**Comment by pc223** [comment]
> Could you simply add task link to WindowsSettings.json instead of creating a new json file, but with a different Type? That will reduce the codebase we need to take care on.😉

Yeah no problem, just I'm not sure about the schema, what is the schema you want?

**Comment by taooceros** [comment]
The same schema as other windows settings?

**Comment by pc223** [comment]
> The same schema as other windows settings?

Do you want the keywords list? Or only name and command?, and can the name be normal string? I don't know how to deal with Resources.resx

```json
    {
      "name": "View scanners and cameras",
      "cmd": "%ProgramFiles%\\Windows Photo Viewer\\ImagingDevices.exe",
      "keywords": [
        [
          "camaras",
          "cameras",
          "camras"
        ],
        [
          "automatically",
          "autoshow",
          "auto-show",
          "make",
          "visible",
          "see",
          "show",
          "unlock",
          "view"
        ],
        [
          "check",
          "list",
          "see",
          "show",
          "viewing"
        ]
      ]
    }
```

**Comment by taooceros** [comment]
The keyword list looks a bit too overmatch?

**Comment by taooceros** [comment]
I am not sure the the resource either, but I think you can edit it with rider. Edit the resource.resx file in properties folder.

**Comment by pc223** [comment]
> The keyword list looks a bit too overmatch?

Yeah, this is come straight from Microsoft, not my creation haha. Not sure exactly why MS have this, probably related to Score compute algorithm

**Comment by pc223** [comment]
> I am not sure the the resource either, but I think you can edit it with rider. Edit the resource.resx file in properties folder.

I'll try to look in the the resx file later, but can we do normal string for now, like this plugin will check if the name exist in the resx, if not then use it as normal string.

**Comment by taooceros** [comment]
Sure, I also only do the translation after finishing all other changes.

**Pull request closed without merging**
